### ISSUE TITLE
Not able to sign-up in public instance

### ISSUE THREAD

**Issue by adamjanovsky** [BorysekOndrej/bakalarka-general#1]
Hello,

I'm currently doing a reader's review on your Bachelor's thesis. I wanted to go through the public instance on tlsinventory.com, maybe test some sites, etc. Sadly, I'm not able to register with the service. Submitting the registration form does not seem to trigger any actions. Please let me know if this is a known issue, and if you intend to fix this soonish.

**Comment by BorysekOndrej** [comment]
Hello, thanks for reaching out.
The primary issue is that the container for the API server got killed by something on the host system. When I correlate the timestamps of the last messages from server logs and the RAM utilization graph, it clearly points out a sudden spike in RAM utilization (from 35% to 100%) at that time that lasted less than 5 minutes. So it most likely got killed by the Out Of Memory killer. This is a known issue and mentioned near the end of the thesis as future improvement. I will have it implemented by Monday.

The secondary problem is that my uptime monitoring did not send an alert, because I was monitoring a cached endpoint. Even though the API server was down, cached responses were still being served from a reverse proxy. I'll also have this fixed by Monday.

**Comment by adamjanovsky** [comment]
Great, I'll wait with the review then until this issue is closed.

**Comment by BorysekOndrej** [comment]
This issue is fixed for the public instance and has been running for 2 days without a problem. It seems ok.

Long-term solution for self-hosted instances would be a Python script which would generate the appropriate Docker Compose file based on the amount of RAM and CPU a user is willing to provide. I have PoC, but I'm not yet satisfied with it. The general solution might be docker swarms or Kubernetes, though I'm reluctant to introduce another technology to the stack. For now I've created [issue](https://github.com/TLSInventory/docker/issues/1) from this.
